
title: "Learn-Software.com"

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

languages:
  en:
    languageName: English
    weight: 1
  es:
    languageName: Español
    weight: 2

# Parse Git commit
enableGitInfo: true

markup:
  goldmark:
    duplicateResourceFiles: true
    extensions:
      passthrough:
        delimiters:
          block: [['\[', '\]'], ["$$", "$$"]]
          inline: [['\(', '\)']]
        enable: true
    renderer:
      unsafe: true

menu:
  main:
    - identifier: paths
      weight: 1
    - identifier: programming
      pageRef: /programming
      parent: paths
      weight: 1
    - identifier: softwareEngineering
      pageRef: /software-engineering
      parent: paths
      weight: 2
    - identifier: artificialIntelligence
      pageRef: /ai
      parent: paths
      weight: 3
    # - identifier: devops
    #   pageRef: /devops
    #   parent: paths
    #   weight: 4
    # - identifier: quantum
    #   pageRef: /quantum
    #   parent: paths
    #   weight: 5
    - identifier: blog
      pageRef: /blog
      weight: 2
    # - identifier: about
    #   pageRef: /about
    #   weight: 3
    - identifier: search
      weight: 4
      params:
        type: search
    - identifier: glossary
      weight: 5
      pageRef: /glossary
      params:
        icon: book-open
    - identifier: languageSwitcher
      weight: 6
      params:
        type: language-switch
        label: false
        icon: "globe"
    - identifier: themeToggle
      weight: 7
      params:
        type: theme-toggle
        label: false
    - name: GitHub
      weight: 8
      url: "https://github.com/learn-software-engineering"
      params:
        icon: github

outputs:
  home: [html, llms]
  page: [html, markdown]
  section: [html, rss, markdown]
